### create users
post http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "Alexlala",
    "name": "Arto Hellas",
    "password": "122"

}
### create blogs
post http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "addadasdadasdadadad",
    "author": "Michael Chan",
    "url": "https://reactpatterns.com/",
    "likes": 7
}

### log-in
post http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "Alexlala",
    "password": "122"
}

### create blogs with token authentication
post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFsZXhsYWxhIiwiaWQiOiI2OWRkZjA2Zjc3MGEwMzNiOTRkNjUxNjciLCJpYXQiOjE3NzYyMzcyNzd9.W7ghN0LabAdjzWV5aAwZD6DoWc-TctT5OPrWoFZXYQU

{
    "title": "ZZZZZZZZZZZZZZZZZZz",
    "author": "Alex",
    "url": "https://reactpatterns.com/",
    "likes": 7
}

### delete a blog
DELETE http://localhost:3003/api/blogs/69e09a604957c20bb0504a5c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFsZXhsYWxhIiwiaWQiOiI2OWRkZjA2Zjc3MGEwMzNiOTRkNjUxNjciLCJpYXQiOjE3NzYyMzcyNzd9.W7ghN0LabAdjzWV5aAwZD6DoWc-TctT5OPrWoFZXYQU

