### create users
post http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "Alexlala",
    "name": "Arto Hellas",
    "password": "122"

}
### create blogs
post http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "addadasdadasdadadad",
    "author": "Michael Chan",
    "url": "https://reactpatterns.com/",
    "likes": 7
}